 const AfternoonDetail = [
    {
        "TeeBox": "1",
        "Flight": 1,
        "Status": "N",
        "TeeTime": "11:08:00",
        "children": {
            "blockMap": [
                {
                    "Remark": "CLOSE CORING DESERT",
                    "Color": 8454143
                }
            ],
            "bookMap": []
        }
    },
    {
        "TeeBox": "1",
        "Flight": 2,
        "Status": "N",
        "TeeTime": "11:16:00",
        "children": {
            "blockMap": [
                {
                    "Remark": "CLOSE CORING DESERT",
                    "Color": 8454143
                }
            ],
            "bookMap": []
        }
    },
    {
        "TeeBox": "1",
        "Flight": 3,
        "Status": "N",
        "TeeTime": "11:24:00",
        "children": {
            "blockMap": [
                {
                    "Remark": "CLOSE CORING DESERT",
                    "Color": 8454143
                }
            ],
            "bookMap": []
        }
    },
    {
        "TeeBox": "1",
        "Flight": 4,
        "Status": "N",
        "TeeTime": "11:32:00",
        "children": {
            "blockMap": [
                {
                    "Remark": "CLOSE CORING DESERT",
                    "Color": 8454143
                }
            ],
            "bookMap": []
        }
    },
    {
        "TeeBox": "1",
        "Flight": 5,
        "Status": "N",
        "TeeTime": "11:40:00",
        "children": {
            "blockMap": [],
            "bookMap": [
                {
                    "BookingID": "90323-026",
                    "GuestType": "Visitor",
                    "Name": "MS DO NGOC MAI",
                    "details": [
                        {
                            "Counter": 1,
                            "GuestType": "Ladies",
                            "MemberNo": "",
                            "Name": "MS DO NGOC MAI"
                        },
                        {
                            "Counter": 2,
                            "GuestType": "Visitor",
                            "MemberNo": "",
                            "Name": "PHAM DANH"
                        }
                    ]
                }
            ]
        }
    },
    {
        "TeeBox": "1",
        "Flight": 6,
        "Status": "N",
        "TeeTime": "11:48:00",
        "children": {
            "blockMap": [],
            "bookMap": [
                {
                    "BookingID": "90323-040",
                    "GuestType": "Visitor",
                    "Name": "MR DUY",
                    "details": [
                        {
                            "Counter": 1,
                            "GuestType": "Visitor",
                            "MemberNo": "",
                            "Name": "CAO NGUYEN TRIEU DUY"
                        },
                        {
                            "Counter": 2,
                            "GuestType": "Visitor",
                            "MemberNo": "",
                            "Name": "CAO VAN CHINH"
                        },
                        {
                            "Counter": 3,
                            "GuestType": "Visitor",
                            "MemberNo": "",
                            "Name": "CAO MINH THUC"
                        },
                        {
                            "Counter": 4,
                            "GuestType": "Reciprocal Clubs",
                            "MemberNo": "",
                            "Name": "CAO VAN VO (BGC)"
                        }
                    ]
                }
            ]
        }
    },
 ];